name: CI on main
on:
  push:
    branches:
      - "main"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
